# Week 6 activities: Data wrangling using pandas

# Setup

In [2]:
# packages
import pandas as pd
import numpy as np
import os

from IPython.core.interactiveshell import InteractiveShell
InteractiveShell.ast_node_interactivity = "all"

# Load the data: you'll need to edit your path
# I recommend moving this notebook into your "myactivities" repo, 
# creating a folder in that repo for data, moving the data there, and loading from there

In [ ]:

os.getcwd()

In [4]:
from pathlib import Path
DATA_PATH = Path("../datasets/")
os.chdir(DATA_PATH)
os.getcwd()

'/Users/rj545/Dropbox/PPOL5203_fall2026/datasets'

In [ ]:
os.listdir()

In [5]:
df = pd.read_csv("childnoinsur_complete.csv")
df.head()

,State,Race,Year,uninsured_rate,Census_Division
0,Wyoming,Non-Hispanic White,2018,0.07,Mountain
1,Wyoming,Hispanic or Latino,2018,0.06,Mountain
2,Wyoming,Black or African American,2018,0.02,Mountain
3,Wyoming,Asian and Pacific Islander,2018,0.02,Mountain
4,Wisconsin,Two or more races,2018,0.02,East North Central

# Activity 1: attributes of dataframes

Using the data loaded above, answer the following questions:

A. What are the unique racial/ethnic categories in the data?

B. What is the maximum and minimum child uninsurance rate?

C. What is the earliest and latest year in the data?

D. Which state(s) has the most observations? Which state(s) has the fewest? (note: this version of the dataset omits state-row-categories with missing data on the uninsurance rate; next week, we'll work with a version that retains observations with those missing values)

*Hint*: for part D you may want to use sort_values() - documentation is here: https://pandas.pydata.org/docs/reference/api/pandas.DataFrame.sort_values.html

In [ ]:
## your code here

# Activity 2: selecting and filtering

A. Subset the data to the State == `California`. Store the resulting dataframe as `ca_df` and use the `shape` command to print the dimensions

In [ ]:
## your code here

B. Use list comprehension and the `columns` attribute to create a list of columns, called `cols_keep` that excludes the following two columns: 
- `State`
- `Census_Division`

Print the list. It should contain columns for Race, Year, and uninsured_rate

In [ ]:
## your code here

C. Use the `cols_keep` list to create a new dataset, `ca_df_clean` that removes those two columns. Print the head

In [ ]:
## your code here

D. Write a user-defined function, `subset_onerace` that takes in three arguments:
- A string for a racial/ethnic group
- A string representing the name of the race/ethnicity column
- A dataframe

And subset the data to rows of data for that race/ethnicity

E. Use that user-defined function to return the rows for `American Indian or Alaska Native`, ordered by year from lowest to highest. Has the uninsurance rate among children gone up or down over time?

In [ ]:
## your code here

F. Using list comprehension, iterate over the unique race/ethnicity groups in `ca_df_clean` and apply that function to create a subset of rows ordered by year for that group; the result will be a list of dataframes

Print the result; what patterns do you notice?

In [ ]:
## your code here

# Activity 3: creating and recoding variables

A. Going back to the full dataset, `df`, create a new variable in the dataset, `race_simplified`, that:

- Converts the string to lowercase
- Replaces spaces with _ 

Use `pd.crosstab` with the two variables to make sure the recoding worked

In [ ]:
## your code here

B. In the full dataset, use `np.mean` to find the nationwide average uninsurance rate. Create a variable, `ur_demean` that subtracts that national average from each individual `uninsured_rate`

Use .describe() to confirm the de-meaning worked (the overall variable mean should be very close to zero and min and max should change)

In [ ]:
## your code here

C. In the full dataset, use `np.select` to create a new variable, `type_statename` that codes state names into two categories:
    
    - two_words: if the name has multiple words (eg North Carolina, New Jersey, etc)
    - one_word: if the name has a single word
        
Hint: you can do this by checking whether the name string contains any spaces, comparing the length of the string to the number of alpha characters, or another approach

Spot check your work using the `sample` command

In [ ]:
## your code here

# Activity 4: grouping and aggregation

A. Group the dataset by `Census_Division`. Use a for loop to print the group names

In [6]:
## your code here
cd_groups = df.groupby('Census_Division')
for group, data in cd_groups:
    print(group)

East North Central
East South Central
Middle Atlantic
Mountain
New England
Pacific
South Atlantic
West North Central
West South Central

B. Use `get_group` to extract the Pacific region group and find the mean `uninsured_rate` for states/years/racial/ethnic groups in that group

In [10]:
## your code here
pacific_group = cd_groups.get_group('Pacific')
pacific_group.uninsured_rate.mean()
pacific_group['uninsured_rate'].mean()

0.043093922651933694

0.043093922651933694

C. Going back to the full dataset, group by `Census_Division` and find the mean uninsurance rate within that group across all states/years. Was the Mountain region higher or lower than other regions in terms of its child uninsurance rate? Which region has the lowest uninsurance rate?

In [11]:
## your code here
df.groupby('Census_Division')['uninsured_rate'].mean().reset_index().sort_values(by = 
                                                        'uninsured_rate')

      Census_Division  uninsured_rate
4         New England        0.027202
2     Middle Atlantic        0.037542
5             Pacific        0.043094
0  East North Central        0.044433
7  West North Central        0.055702
1  East South Central        0.056571
6      South Atlantic        0.058029
3            Mountain        0.070117
8  West South Central        0.084832

In [14]:
df.groupby('Census_Division').agg({'uninsured_rate':
                                   ['mean', 'median']}).reset_index()

      Census_Division uninsured_rate
                                mean median
0  East North Central       0.044433   0.04
1  East South Central       0.056571   0.04
2     Middle Atlantic       0.037542   0.03
3            Mountain       0.070117   0.06
4         New England       0.027202   0.02
5             Pacific       0.043094   0.03
6      South Atlantic       0.058029   0.05
7  West North Central       0.055702   0.05
8  West South Central       0.084832   0.07

D. Use `groupby` and the built-in `idxmax` aggregation function to:
    
- Group by race/ethnic group (`Race`)
- Find the year and state with the highest uninsurance rate for that race/ethnic group

Hint: there are multiple approaches for how to pull the columns tied to the row with the maximum uninsurance rate, including .loc and sort_values()

In [18]:
## your code here
index_max = df.groupby('Race')['uninsured_rate'].idxmax()
index_max

df.loc[index_max, ['Race', 'State', 'Year', 'uninsured_rate']]

Race
American Indian or Alaska Native    1219
Asian and Pacific Islander          1208
Black or African American            762
Hispanic or Latino                   949
Non-Hispanic White                   956
Two or more races                    957
Name: uninsured_rate, dtype: int64

                                  Race      State  Year  uninsured_rate
1219  American Indian or Alaska Native    Arizona  2019            0.24
1208        Asian and Pacific Islander   Arkansas  2019            0.15
762          Black or African American    Arizona  2024            0.13
949                 Hispanic or Latino  Tennessee  2024            0.20
956                 Non-Hispanic White      Texas  2024            0.09
957                  Two or more races      Texas  2024            0.16

E. Use `groupby`, `agg`, and a lambda function to:

- Group by race/ethnic group (`Race`)
- Find the interquartile range of uninsurance rates for each race/ethnicity group across states and years. Which groups vary the most?

In [19]:
## your code here 
df.groupby('Race').agg(ur_iqr = ('uninsured_rate',
                                lambda x: x.quantile(0.75) - x.quantile(0.25)))

                                  ur_iqr
Race
American Indian or Alaska Native    0.08
Asian and Pacific Islander          0.03
Black or African American           0.02
Hispanic or Latino                  0.06
Non-Hispanic White                  0.02
Two or more races                   0.03